const data = [
  {
    label: "Alabama",
    population: 4780127,
    capital: "Montgomery",
    region: "South",
    body: "<p>Alabama, known as the 'Heart of Dixie,' is a state rich in American history and culture. Montgomery, the state's capital, played a significant role in the Civil Rights Movement, with landmarks such as the Rosa Parks Museum and the Dexter Avenue Baptist Church.</p><p>Alabama's diverse geography spans from coastal plains to mountainous regions, offering beautiful natural scenery. The state is also known for its vibrant music scene, with roots in jazz, blues, and country music, and for its deep ties to college football, especially the University of Alabama's Crimson Tide.</p>",
  },
  {
    label: "Alaska",
    population: 710249,
    capital: "Juneau",
    region: "West",
    body: "<p>Alaska, the largest state by area, is known for its rugged landscapes, vast wilderness, and abundant wildlife. Its capital, Juneau, is only accessible by sea or air and is surrounded by stunning glaciers and mountains.</p><p>Famous for its oil reserves and seafood industry, Alaska is a vital contributor to the U.S. economy. The state is also home to indigenous cultures, with diverse traditions and languages, and is a prime destination for outdoor activities like fishing, hunting, and dog sledding.</p>",
  },
  {
    label: "Arizona",
    population: 6392307,
    capital: "Phoenix",
    region: "West",
    body: "<p>Arizona is home to the Grand Canyon, one of the Seven Natural Wonders of the World, and offers a landscape full of desert beauty and iconic red rock formations. The state's capital, Phoenix, is one of the fastest-growing cities in the U.S. and a major center for technology and innovation.</p><p>In addition to its stunning natural scenery, Arizona has a rich Native American history, with many tribal lands and cultural sites. The state's unique climate and landscape attract millions of tourists annually, especially those seeking warmth during the winter months.</p>",
  },
  {
    label: "Arkansas",
    population: 2915958,
    capital: "Little Rock",
    region: "South",
    body: "<p>Arkansas, known as 'The Natural State,' is famous for its diverse outdoor attractions, including the Ozark and Ouachita mountains, and numerous rivers, lakes, and hot springs. Little Rock, the state's capital, is a hub of history and culture with landmarks like the Little Rock Central High School National Historic Site.</p><p>Economically, Arkansas is a leader in agriculture, particularly poultry and rice farming. The state is also the headquarters of Walmart, the world's largest retailer, adding to its economic significance on both a national and global scale.</p>",
  },
  {
    label: "California",
    population: 37254503,
    capital: "Sacramento",
    region: "West",
    body: "<p>California, the most populous state, is an economic powerhouse and home to Silicon Valley, the heart of the tech industry. Sacramento, the state's capital, lies in the fertile Central Valley and has a rich history dating back to the Gold Rush era.</p><p>Known for its diversity in culture and geography, California offers everything from beaches and mountains to deserts and redwood forests. Major cities like Los Angeles and San Francisco are globally recognized for their influence in entertainment, technology, and lifestyle.</p>",
  },
  {
    label: "Colorado",
    population: 5029324,
    capital: "Denver",
    region: "West",
    body: "<p>Colorado is known for its breathtaking Rocky Mountain scenery and is a premier destination for outdoor enthusiasts. Denver, the state's capital, is a vibrant city that combines modern amenities with a rugged Western feel, offering access to both cultural attractions and mountain adventures.</p><p>The state has a strong economy driven by industries such as technology, aerospace, and tourism. Colorado's diverse climate and scenic landscapes make it a year-round destination, with skiing, hiking, and mountain biking among its popular recreational activities.</p>",
  },
  {
    label: "Connecticut",
    population: 3574118,
    capital: "Hartford",
    region: "Northeast",
    body: "<p>Connecticut, one of the original 13 colonies, is steeped in colonial history and known for its charming towns and scenic coastal views. Hartford, the capital, is known as the 'Insurance Capital of the World,' with a significant role in the finance and insurance industries.</p><p>With a mix of urban and rural areas, Connecticut offers cultural attractions such as museums, theaters, and historic sites. The state is also home to prestigious universities, including Yale, which contributes to its strong educational reputation.</p>",
  },
  {
    label: "Delaware",
    population: 897936,
    capital: "Dover",
    region: "South",
    body: "<p>Delaware, the first state to ratify the U.S. Constitution, is known for its historical significance and tax-friendly business environment. Dover, the capital, features historic buildings and is home to the annual Dover International Speedway events.</p><p>Although small in size, Delaware has a vibrant economy driven by banking, chemical manufacturing, and agriculture. Its beaches, especially in the Rehoboth area, are popular tourist destinations along the Atlantic coast.</p>",
  },
  {
    label: "Florida",
    population: 18804623,
    capital: "Tallahassee",
    region: "South",
    body: "<p>Florida, known as the 'Sunshine State,' attracts millions of visitors with its warm climate, beautiful beaches, and famous theme parks. Tallahassee, the capital, has a rich history and is a center for education, being home to Florida State University and Florida A&M University.</p><p>The state's economy is heavily supported by tourism, agriculture, and aerospace. Florida is also known for its diverse wildlife, particularly in the Everglades, a unique ecosystem with a mix of freshwater and saltwater habitats.</p>",
  },
  {
    label: "Georgia",
    population: 9688681,
    capital: "Atlanta",
    region: "South",
    body: "<p>Georgia, known as the 'Peach State,' boasts a diverse landscape from mountains to coastal marshes. Atlanta, the state's capital, is a major cultural and economic hub, home to global companies like Coca-Cola and Delta Airlines, as well as key historical sites related to the Civil Rights Movement.</p><p>The state's economy is driven by agriculture, manufacturing, and transportation. With a warm climate and Southern charm, Georgia has become an attractive destination for residents and tourists alike.</p>",
  },
  {
    label: "Hawaii",
    population: 1360301,
    capital: "Honolulu",
    region: "West",
    body: "<p>Hawaii, the only U.S. state composed entirely of islands, is known for its unique Polynesian culture, tropical climate, and stunning beaches. Honolulu, located on the island of Oahu, is the state capital and a major hub for tourism, particularly at famous sites like Waikiki Beach and Pearl Harbor.</p><p>As the birthplace of modern surfing, Hawaii has a vibrant outdoor culture and is known for its volcanoes, including the active Kilauea volcano on the Big Island. The state's economy is heavily driven by tourism, military defense, and agriculture, particularly pineapple and sugarcane.</p>",
  },
  {
    label: "Idaho",
    population: 1567652,
    capital: "Boise",
    region: "West",
    body: "<p>Idaho, known as the 'Gem State,' is celebrated for its rugged mountains, vast forests, and outdoor recreation opportunities. Boise, the state's capital, is a rapidly growing city with a mix of cultural attractions, vibrant local art, and a strong connection to nature.</p><p>Economically, Idaho is a significant agricultural state, particularly known for its potatoes. The state is also rich in natural resources, with mining, forestry, and technology sectors playing important roles in its economy. Idaho's rivers and mountainous landscapes make it a destination for fishing, skiing, and hiking.</p>",
  },
  {
    label: "Illinois",
    population: 12831549,
    capital: "Springfield",
    region: "Midwest",
    body: "<p>Illinois is a state with a rich history and a diverse economy, ranging from agriculture in its rural areas to finance and industry in cities like Chicago. Springfield, the capital, is known for its connection to Abraham Lincoln, with many historical sites dedicated to the 16th U.S. president.</p><p>Chicago, Illinois' largest city, is a global metropolis with cultural, economic, and architectural significance. The state is also a leader in manufacturing, technology, and education, with several renowned universities. Illinois' central location makes it a transportation hub in the Midwest.</p>",
  },
  {
    label: "Indiana",
    population: 6484229,
    capital: "Indianapolis",
    region: "Midwest",
    body: "<p>Indiana, often called the 'Crossroads of America,' has a strong agricultural and manufacturing base. Indianapolis, the state capital, is known for the Indianapolis 500, one of the most famous automobile races in the world, drawing fans from across the globe.</p><p>The state's economy is driven by diverse industries, including pharmaceuticals, transportation, and agriculture, particularly corn and soybeans. Indiana is also known for its friendly communities, basketball culture, and scenic countryside, making it an attractive place to live and visit.</p>",
  },
  {
    label: "Iowa",
    population: 3046869,
    capital: "Des Moines",
    region: "Midwest",
    body: "<p>Iowa, often referred to as the 'Corn State,' is a major agricultural hub, with vast fields of corn and soybeans dominating its landscape. Des Moines, the state capital, is a growing city with a strong presence in the insurance and finance industries.</p><p>Agriculture remains the backbone of Iowa's economy, but the state has also developed a tech sector in recent years. Known for its friendly, rural communities and cultural events like the Iowa State Fair, Iowa offers a blend of Midwestern charm and agricultural heritage.</p>",
  },
  {
    label: "Kansas",
    population: 2853132,
    capital: "Topeka",
    region: "Midwest",
    body: "<p>Kansas, often associated with the vast Great Plains, has a strong agricultural economy with wheat as one of its primary crops. Topeka, the state capital, is known for its role in the landmark Brown v. Board of Education case, which helped end racial segregation in U.S. schools.</p><p>Known as the 'Sunflower State,' Kansas has a diverse landscape that includes prairies, rolling hills, and forests. The state's economy is largely based on agriculture and aviation, with Wichita being a major center for the aerospace industry. Kansas is also celebrated for its rich history and Western heritage.</p>",
  },
  {
    label: "Kentucky",
    population: 4339349,
    capital: "Frankfort",
    region: "South",
    body: "<p>Kentucky, known as the 'Bluegrass State,' is famous for its horse racing, bourbon distilleries, and lush landscapes. The capital, Frankfort, is a charming town that celebrates Kentucky's rich history and its ties to the state's equestrian culture.</p><p>Each year, the Kentucky Derby, held in Louisville, draws worldwide attention as the premier horse racing event in the U.S. Kentucky is also known for its contributions to the tobacco and automobile industries, as well as for natural wonders like Mammoth Cave, the longest cave system in the world.</p>",
  },
  {
    label: "Louisiana",
    population: 4533479,
    capital: "Baton Rouge",
    region: "South",
    body: "<p>Louisiana is celebrated for its unique Creole and Cajun cultures, deeply influenced by French, Spanish, and African heritage. Baton Rouge, the state capital, is a city rich in history and home to Louisiana State University, adding to its lively atmosphere.</p><p>New Orleans, the state's largest city, is world-famous for its Mardi Gras festival, jazz music, and vibrant culinary scene. Louisiana's economy is driven by industries like petrochemicals, agriculture, and tourism, while its bayous, swamps, and distinctive cuisine make it a truly unique part of the United States.</p>",
  },
  {
    label: "Maine",
    population: 1328361,
    capital: "Augusta",
    region: "Northeast",
    body: "<p>Maine, known as the 'Pine Tree State,' is famous for its scenic coastline, fresh seafood, and picturesque landscapes. The capital, Augusta, sits along the Kennebec River and is known for its rich colonial history and historical landmarks.</p><p>Tourism is a major industry in Maine, especially in coastal towns and at Acadia National Park, where visitors enjoy hiking, boating, and breathtaking ocean views. Maine is also a top producer of lobster, with its seafood industry being a crucial part of the state's economy.</p>",
  },
  {
    label: "Maryland",
    population: 5773785,
    capital: "Annapolis",
    region: "South",
    body: "<p>Maryland, often called 'America in Miniature,' offers a wide variety of landscapes, from beaches to mountains. Annapolis, the capital, is known for its colonial architecture and is home to the United States Naval Academy, reflecting the state's rich maritime history.</p><p>Maryland has a diverse economy, driven by sectors such as biotechnology, aerospace, and healthcare, with a close connection to the federal government due to its proximity to Washington, D.C. The Chesapeake Bay plays an important role in the state's identity, supporting a thriving seafood industry, particularly known for blue crabs.</p>",
  },
  {
    label: "Massachusetts",
    population: 6547817,
    capital: "Boston",
    region: "Northeast",
    body: "<p>Massachusetts, known as the 'Bay State,' is steeped in American history and education. Boston, the state capital, played a pivotal role in the American Revolution and is home to world-renowned institutions such as Harvard University and the Massachusetts Institute of Technology (MIT).</p><p>The state's economy is strong, with industries in technology, finance, and healthcare. Massachusetts offers diverse landscapes, from the sandy beaches of Cape Cod to the scenic Berkshires, and is known for its vibrant arts scene, historical landmarks, and cultural significance.</p>",
  },
  {
    label: "Michigan",
    population: 9884129,
    capital: "Lansing",
    region: "Midwest",
    body: "<p>Michigan, known as the 'Great Lakes State,' is bordered by four of the five Great Lakes, giving it the longest freshwater coastline of any political subdivision in the world. Lansing, the capital, is a center of government and education, home to Michigan State University.</p><p>Detroit, Michigan's largest city, is famous as the birthplace of the automotive industry and Motown music. The state offers diverse natural beauty, from forests to sand dunes, and its economy is supported by manufacturing, agriculture, and tourism, especially related to outdoor activities.</p>",
  },
  {
    label: "Minnesota",
    population: 5303925,
    capital: "Saint Paul",
    region: "Midwest",
    body: "<p>Minnesota, known as the 'Land of 10,000 Lakes,' offers abundant natural beauty and outdoor recreation opportunities. Saint Paul, the state capital, is part of the Twin Cities with neighboring Minneapolis, creating a vibrant cultural and economic hub.</p><p>The state's economy is diverse, with key industries including healthcare, technology, and agriculture. Minnesota is known for its high quality of life, excellent educational institutions, and a strong Scandinavian influence, particularly evident in its architecture, food, and festivals.</p>",
  },
  {
    label: "Mississippi",
    population: 2968103,
    capital: "Jackson",
    region: "South",
    body: "<p>Mississippi, often called the 'Magnolia State,' is known for its role in American history, especially in the context of the Civil Rights Movement. Jackson, the state capital, is home to several museums and landmarks that commemorate this rich and complex history.</p><p>The state is also renowned for its contributions to music, particularly blues, with Mississippi often recognized as the birthplace of the genre. Agriculture, particularly cotton, and forestry play major roles in the economy, while the Mississippi River remains a vital resource for trade and tourism.</p>",
  },
  {
    label: "Missouri",
    population: 5988927,
    capital: "Jefferson City",
    region: "Midwest",
    body: "<p>Missouri, known as the 'Show Me State,' offers a blend of Midwest and Southern cultures. Jefferson City, the capital, is known for its beautiful capitol building overlooking the Missouri River, as well as its historical significance.</p><p>The state's largest cities, St. Louis and Kansas City, are cultural and economic centers, known for their music, barbecue, and sports teams. Missouri's economy includes agriculture, manufacturing, and transportation, supported by the state's strategic location in the center of the U.S.</p>",
  },
  {
    label: "Montana",
    population: 989417,
    capital: "Helena",
    region: "West",
    body: "<p>Montana, known as 'Big Sky Country,' is famous for its vast landscapes, including the Rocky Mountains, prairies, and pristine national parks like Glacier and Yellowstone. Helena, the state capital, has a rich history from its days as a gold rush town and offers access to the state's outdoor beauty.</p><p>The economy of Montana is heavily reliant on agriculture, mining, and tourism, with outdoor activities like hiking, skiing, and fishing attracting visitors year-round. Montana's commitment to conservation and its spectacular natural resources make it a beloved destination for nature lovers.</p>",
  },
  {
    label: "Nebraska",
    population: 1826341,
    capital: "Lincoln",
    region: "Midwest",
    body: "<p>Nebraska, often called the 'Cornhusker State,' is known for its wide-open prairies and its role as a key agricultural center in the U.S. Lincoln, the state capital, is a vibrant city with a rich history and serves as a cultural and educational hub, home to the University of Nebraska.</p><p>Agriculture, especially corn and beef production, is central to Nebraska's economy. The state is also known for its sandhill crane migration along the Platte River, which attracts bird-watchers from around the world each year.</p>",
  },
  {
    label: "Nevada",
    population: 2700691,
    capital: "Carson City",
    region: "West",
    body: "<p>Nevada, famously known as the 'Silver State,' is renowned for its desert landscapes and entertainment hubs, most notably Las Vegas and Reno. Carson City, the state capital, is nestled near Lake Tahoe, offering a mix of natural beauty and Nevada’s distinctive Western culture.</p><p>The state's economy is heavily supported by tourism, particularly through its casinos and hospitality industry. Nevada is also rich in natural resources, including silver and other minerals, while outdoor recreation like hiking and skiing are popular among residents and visitors alike.</p>",
  },
  {
    label: "New Hampshire",
    population: 1316466,
    capital: "Concord",
    region: "Northeast",
    body: "<p>New Hampshire, known as the 'Granite State,' is famous for its rugged landscapes, charming small towns, and the White Mountains. Concord, the state capital, has a rich colonial history and is a center of New Hampshire’s government and culture.</p><p>Tourism is a major part of New Hampshire’s economy, with visitors flocking to the state for activities like skiing, hiking, and leaf-peeping in the fall. The state is also known for its political prominence, as it holds the first primary in the U.S. presidential election cycle.</p>",
  },
  {
    label: "New Jersey",
    population: 8791936,
    capital: "Trenton",
    region: "Northeast",
    body: "<p>New Jersey, known as the 'Garden State,' boasts a diverse economy, beautiful shorelines, and close proximity to both New York City and Philadelphia. Trenton, the state capital, has historical significance as a key location during the American Revolution.</p><p>The state's economy is varied, with strong sectors in pharmaceuticals, finance, and manufacturing. Known for its beaches along the Jersey Shore, New Jersey also offers cultural and natural attractions, including the Pine Barrens and a bustling arts scene in cities like Newark.</p>",
  },
  {
    label: "New Mexico",
    population: 2059192,
    capital: "Santa Fe",
    region: "West",
    body: "<p>New Mexico, known as the 'Land of Enchantment,' is celebrated for its unique blend of Native American, Hispanic, and Anglo cultures. Santa Fe, the state capital, is famous for its adobe architecture, art galleries, and vibrant cultural scene.</p><p>The state’s economy includes industries such as oil and gas, tourism, and film production. New Mexico’s stunning landscapes, which range from deserts to mountains, attract outdoor enthusiasts and those interested in the state’s rich history and heritage.</p>",
  },
  {
    label: "New York",
    population: 19378087,
    capital: "Albany",
    region: "Northeast",
    body: "<p>New York, often referred to as the 'Empire State,' is home to one of the most iconic cities in the world, New York City. Albany, the state capital, is located along the Hudson River and has a rich political and economic history.</p><p>The state's economy is diverse, with finance, media, and technology sectors centered in New York City, while upstate New York is known for its natural beauty, agriculture, and higher education institutions. New York’s cultural significance, historical landmarks, and attractions make it a global destination.</p>",
  },
  {
    label: "North Carolina",
    population: 9535692,
    capital: "Raleigh",
    region: "South",
    body: "<p>North Carolina, often called the 'Tar Heel State,' is known for its diverse geography, from the Blue Ridge Mountains to the Atlantic coastline. Raleigh, the capital, is part of the Research Triangle with Durham and Chapel Hill, a major center for technology and research.</p><p>The state has a robust economy supported by industries such as finance, biotechnology, and higher education. North Carolina is also famous for its vibrant arts and music scene, historic landmarks, and natural beauty, making it a popular destination for both residents and tourists.</p>",
  },
  {
    label: "North Dakota",
    population: 672591,
    capital: "Bismarck",
    region: "Midwest",
    body: "<p>North Dakota, known as the 'Peace Garden State,' is celebrated for its sweeping plains, Badlands, and agricultural productivity. Bismarck, the capital, sits on the Missouri River and offers a mix of historical sites and outdoor activities.</p><p>The state’s economy relies heavily on agriculture and energy production, with a booming oil industry in recent years. North Dakota’s wide-open spaces and scenic landscapes, including Theodore Roosevelt National Park, attract outdoor enthusiasts looking for a rugged, natural escape.</p>",
  },
  {
    label: "Ohio",
    population: 11536725,
    capital: "Columbus",
    region: "Midwest",
    body: "<p>Ohio, known as the 'Buckeye State,' is a key industrial and cultural hub in the Midwest. Columbus, the capital, is one of the fastest-growing cities in the U.S., with a dynamic economy driven by education, healthcare, and technology.</p><p>Ohio has a rich industrial history, especially in manufacturing and automotive production. The state is also known for its sports culture, vibrant arts scene, and historical landmarks, including those related to aviation pioneers, the Wright brothers, who were from Dayton, Ohio.</p>",
  },
  {
    label: "Oklahoma",
    population: 3751616,
    capital: "Oklahoma City",
    region: "South",
    body: "<p>Oklahoma, often referred to as the 'Sooner State,' is known for its Native American heritage and cowboy culture. Oklahoma City, the state capital, has a blend of historical attractions, art museums, and a growing economy centered around energy, aviation, and biotechnology.</p><p>The state's economy is heavily influenced by oil and gas, as well as agriculture. Oklahoma's diverse landscapes range from forests and rolling hills to the Great Plains, making it a unique region with a strong connection to both history and nature.</p>",
  },
  {
    label: "Oregon",
    population: 3831073,
    capital: "Salem",
    region: "West",
    body: "<p>Oregon, known as the 'Beaver State,' is famous for its diverse landscapes, from the rugged Pacific coastline to the lush forests and volcanic mountains. Salem, the capital, is located in the Willamette Valley, one of the state’s key agricultural regions.</p><p>Oregon has a strong focus on environmental conservation and sustainability. The state’s economy is supported by sectors like technology, agriculture, and tourism, with Portland being a major cultural and economic hub known for its art scene, coffee culture, and outdoor activities.</p>",
  },
  {
    label: "Pennsylvania",
    population: 12702887,
    capital: "Harrisburg",
    region: "Northeast",
    body: "<p>Pennsylvania, known as the 'Keystone State,' played a crucial role in American history, particularly during the Revolutionary War. Harrisburg, the state capital, is known for its historical sites and its location along the Susquehanna River.</p><p>The state’s economy is diverse, with major industries in manufacturing, finance, and agriculture. Pennsylvania is home to landmarks like Philadelphia’s Independence Hall and Pittsburgh’s steel heritage, and it’s known for its rich cultural heritage, from the Amish communities to the legacy of steel production.</p>",
  },
  {
    label: "Rhode Island",
    population: 1052931,
    capital: "Providence",
    region: "Northeast",
    body: "<p>Rhode Island, known as the 'Ocean State,' is the smallest state in the U.S. but rich in history and coastal beauty. Providence, the state capital, is known for its vibrant arts scene, colonial history, and prestigious universities like Brown University.</p><p>The state’s economy is driven by sectors like healthcare, education, and tourism, with visitors drawn to its charming coastal towns, historic architecture, and beautiful beaches. Rhode Island’s close-knit communities and maritime culture make it a unique part of New England.</p>",
  },
  {
    label: "South Carolina",
    population: 4625401,
    capital: "Columbia",
    region: "South",
    body: "<p>South Carolina, known as the 'Palmetto State,' offers a mix of historic charm and scenic beauty from its coastline to its mountain regions. Columbia, the state capital, is a center for government and education, home to the University of South Carolina.</p><p>The state’s economy includes industries such as aerospace, automotive manufacturing, and tourism, with popular destinations like Charleston and Myrtle Beach. South Carolina’s history is deeply tied to the American Revolution and Civil War, and it is known for its Southern hospitality and cultural heritage.</p>",
  },
  {
    label: "South Dakota",
    population: 814191,
    capital: "Pierre",
    region: "Midwest",
    body: "<p>South Dakota, known as the 'Mount Rushmore State,' is famous for its iconic monument and vast prairies. Pierre, the state capital, is one of the smallest U.S. state capitals by population, located along the Missouri River and offering a relaxed, scenic setting.</p><p>The state’s economy is largely based on agriculture, tourism, and natural resources. South Dakota’s Black Hills region is a major attraction, with sites like Mount Rushmore, Crazy Horse Memorial, and the Badlands drawing visitors from around the world.</p>",
  },
  {
    label: "Tennessee",
    population: 6346275,
    capital: "Nashville",
    region: "South",
    body: "<p>Tennessee, often called the 'Volunteer State,' is renowned for its musical heritage, particularly in country, blues, and rock genres. Nashville, the state capital, is widely regarded as the heart of the country music industry and is home to famous venues like the Grand Ole Opry and the Country Music Hall of Fame.</p><p>The state’s economy is supported by industries such as healthcare, automotive manufacturing, and tourism. Memphis, another major city, is known for its contributions to blues music and as the home of Elvis Presley’s Graceland. Tennessee’s rich culture and scenic beauty make it a unique Southern state.</p>",
  },
  {
    label: "Texas",
    population: 25146105,
    capital: "Austin",
    region: "South",
    body: "<p>Texas, known as the 'Lone Star State,' is the second-largest state in both size and population. Austin, the state capital, is known for its vibrant music scene, tech industry, and unique culture, often summed up in the phrase 'Keep Austin Weird.'</p><p>The state’s economy is one of the largest in the U.S., with strengths in energy, technology, agriculture, and aerospace. Texas is known for its cultural diversity, rich history, and distinct regions, from the deserts of West Texas to the Gulf Coast, making it a unique and influential state.</p>",
  },
  {
    label: "Utah",
    population: 2763888,
    capital: "Salt Lake City",
    region: "West",
    body: "<p>Utah, known as the 'Beehive State,' is celebrated for its stunning natural landscapes, from red rock formations to snow-capped mountains. Salt Lake City, the capital, is known for hosting the 2002 Winter Olympics and as the headquarters of the Church of Jesus Christ of Latter-day Saints.</p><p>Utah’s economy is strong in industries such as technology, mining, and tourism, with its national parks, including Zion and Arches, attracting millions of visitors each year. Utah’s diverse outdoor recreational opportunities and robust economy make it a unique and vibrant state.</p>",
  },
  {
    label: "Vermont",
    population: 625745,
    capital: "Montpelier",
    region: "Northeast",
    body: "<p>Vermont, known as the 'Green Mountain State,' is famous for its picturesque landscapes, including lush forests, rolling hills, and charming small towns. Montpelier, the state capital, is the smallest capital city in the U.S. by population, adding to Vermont’s close-knit, community-oriented feel.</p><p>The state’s economy is supported by agriculture, especially dairy farming and maple syrup production, as well as tourism. Vermont’s dedication to environmental preservation, local arts, and outdoor activities make it a popular destination for those seeking natural beauty and tranquility.</p>",
  },
  {
    label: "Virginia",
    population: 8001045,
    capital: "Richmond",
    region: "South",
    body: "<p>Virginia, known as the 'Old Dominion,' has a rich history deeply rooted in the founding of the United States, with colonial landmarks and Civil War sites throughout the state. Richmond, the state capital, is one of the oldest major cities in the U.S. and has a vibrant arts scene.</p><p>Virginia’s economy is diverse, with significant contributions from government and military, technology, and agriculture. The state is also known for its scenic landscapes, including the Blue Ridge Mountains and Chesapeake Bay, making it a blend of historic and natural attractions.</p>",
  },
  {
    label: "Washington",
    population: 6724543,
    capital: "Olympia",
    region: "West",
    body: "<p>Washington, known as the 'Evergreen State,' is famous for its lush forests, coastal scenery, and vibrant tech industry. Olympia, the state capital, is located along the Puget Sound and has a strong focus on environmental preservation and cultural heritage.</p><p>The state’s economy is bolstered by technology, aerospace, and agriculture, with major companies like Microsoft and Amazon headquartered in Seattle. Washington’s diverse landscape includes mountains, rainforests, and desert areas, making it a popular destination for outdoor enthusiasts.</p>",
  },
  {
    label: "West Virginia",
    population: 1853011,
    capital: "Charleston",
    region: "South",
    body: "<p>West Virginia, often called the 'Mountain State,' is renowned for its rugged terrain and Appalachian culture. Charleston, the state capital, is known for its historic sites, cultural events, and scenic location along the Kanawha River.</p><p>The state’s economy has traditionally relied on coal mining, though it is diversifying with industries such as healthcare and tourism. West Virginia offers beautiful natural landscapes, including state parks and forests, which attract outdoor adventurers and those interested in Appalachian heritage.</p>",
  },
  {
    label: "Wisconsin",
    population: 5687289,
    capital: "Madison",
    region: "West",
    body: "<p>Wisconsin, known as the 'Badger State,' is recognized for its dairy industry, particularly cheese production, earning it the nickname 'America’s Dairyland.' Madison, the capital, is a progressive city known for its university, lakes, and vibrant culture.</p><p>The state’s economy is supported by agriculture, manufacturing, and tourism, with a growing emphasis on technology. Wisconsin’s beautiful landscapes, including the Great Lakes shoreline and rolling farmlands, are central to its identity and appeal to residents and visitors alike.</p>",
  },
  {
    label: "Wyoming",
    population: 563767,
    capital: "Cheyenne",
    region: "West",
    body: "<p>Wyoming, known as the 'Equality State,' was the first state to grant women the right to vote. Cheyenne, the state capital, celebrates its Western heritage with events like Cheyenne Frontier Days, the world’s largest outdoor rodeo and Western celebration.</p><p>The state’s economy relies on mineral extraction, agriculture, and tourism, with natural wonders like Yellowstone and Grand Teton National Parks. Wyoming’s vast open landscapes and commitment to preserving its natural beauty make it a unique and scenic part of the American West.</p>",
  },
];

export default data;
